# Generated by Django 2.0.5 on 2018-08-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180730_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetmodel',
            options={'ordering': ('text',)},
        ),
    ]
