# Generated by Django 2.0.5 on 2018-08-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180801_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tweetmodel',
            name='userID',
        ),
    ]
