# Generated by Django 2.0.5 on 2018-08-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symcrypt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='model_pic',
            field=models.ImageField(default='static/symcrypt/img.jpg', upload_to='static/'),
        ),
    ]
