# Generated by Django 2.0.5 on 2018-08-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symcrypt', '0002_profile_model_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='model_pic',
            new_name='pic',
        ),
    ]
