# Generated by Django 2.0.5 on 2018-08-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symcrypt', '0003_auto_20180808_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pre_phone',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
