# Generated by Django 2.0.5 on 2018-08-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symcrypt', '0004_profile_pre_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(upload_to='app/img'),
        ),
    ]
