# Generated by Django 2.0.5 on 2018-08-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symcrypt', '0005_auto_20180808_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
